# Generated by Django 3.0.8 on 2020-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='new',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='readed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
